### ISSUE TITLE
Fix credential storage

### ISSUE THREAD

**Issue by QuinnyPig** [NTT-DATA-Cloud-Transformation/cfn-github-3rd-party-resource#10]
It looks like this wants hardcoded tokens in the CF stack; would shifting this to use Systems Manager Parameter Store be reasonable instead of contravening CF’s guidance around this?

**Comment by rjlohan** [comment]
+1, suggest we update the docs here to recommend use of Dynamic References in the template for clarity: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html#dynamic-references-ssm-secure-strings

**Comment by richardhboyd** [comment]
secretsmanager:resolve is built for this exact reason. You put the secret name in your template and CFN will fetch it and pass it to the resource. The secret never appears in logs, templates, etc...

I’m not sure that there is an issue here that needs to be fixed.
